### ISSUE TITLE
Purpose of caching in Mapper?

### ISSUE THREAD

**Issue by crzo** [MorphiaOrg/morphia#1149]
Hello,

i just wonder what the purpose of the cache is in the mapper?

I had some troubles retrieving multiple documents via "datastore.find(..).asList()" when the structure is the following:

`
@Entity("a")
class A {
@Id
private ObjectId id;

private int state;
}`

and another entity:

`
@Entity("b")
class B {
@Embedded
private A a;
}`

So when i insert a new document A(state=1),
insert a new document B(with current A),
update the current document A to (state=2),
insert a new document B(with current A, which should be state=2)

i get a list of two B's where the inner A always has state=2. So the first B does not have the state=1 anymore. 

I figured out that this has to do with the caching algorithm.

Can you please explain me if that is on purpose or did i just discover a bug? :-)

Cheers,
Chris

**Comment by crzo** [comment]
Please note that the mongo CLI returns those two B's with different A's in it. (One document with A(state=1) and the other with A(state=2))

Best regards,

Chris

**Comment by evanchooly** [comment]
OK.  So there's a bit of ... history involved here.  The idea behind the cache is that when resolving `@Reference` values, we don't want to be creating new instances for every instance of an object being referenced.  In theory, this reduces memory consumption when using `@Reference`.  Now how this applies in *your* case is that you have `@Embedded` types that have IDs.  These ID/instance pairs are stored in the cache which is later resolved from the cache rather than reloaded from the cursor coming from the database.  

The quick fix is to clear the `@Id` field when setting an instance to an `@Embedded` field.

**Comment by crzo** [comment]
Yes i already applied the quick fix, but maybe we should modify the mapper which should not cache this special case? 

What do you think?

Chris

**Comment by evanchooly** [comment]
Personally, I'm pushing for desupporting `@Reference` altogether and so the need for that cache goes away.  In the short term, because of how that code works it gets tricky to determine with something should be cached or not.

**Comment by alednavab** [comment]
Hello,

What about if we could disable the cache usage through the annotations <code>@Reference</code> and <code>@Embedded</code>, with something like

<code>@Reference(useCache = false)</code>
<code>private Person person;</code>

<code>@Embedded(useCache = false)</code>
<code>private Person person;</code>

In this way, you don't need to do a big effort or magic for exclude special cases.

What do you think?

Alejandro.

**Comment by schube** [comment]
Hello!

I have the exact same problem. But I cannot apply the workaround, because I need to store the ID in the embedded document. So I cannot use "The quick fix is to clear the `@Id` field when setting an instance to an `@Embedded` field.".



Is there any option to turn off the cache?
An annotation? A config file? An environment variable?

In my case, this bug is destroying data, as I found out the hard way today.

Thank you!

**Comment by schube** [comment]
Hi again!

For future reference and for others, who have the same problem.
I think, I know how to disable the Cache. With the options I set a new Cache Factory which returns "false" for every Key. I did it like this.




		MapperOptions options = morphia.getMapper().getOptions();
		options.setCacheFactory(new EntityCacheFactory() {
			
			@Override
			public EntityCache createCache() {
				
				return new EntityCache() {

					@Override
					public Boolean exists(Key<?> k) {
						return false; //return false for every key, since we do not want to use the cache
					}

					@Override
					public void flush() {
						// do nothing
						
					}

					@Override
					public <T> T getEntity(Key<T> k) {
						// do nothing
						return null;
					}

					@Override
					public <T> T getProxy(Key<T> k) {
						// do nothing
						return null;
					}

					@Override
					public void notifyExists(Key<?> k, boolean exists) {
						// do nothing
						
					}

					@Override
					public <T> void putEntity(Key<T> k, T t) {
						// do nothing
						
					}

					@Override
					public <T> void putProxy(Key<T> k, T t) {
						// do nothing
						
					}

					@Override
					public EntityCacheStatistics stats() {
						return new EntityCacheStatistics();
					}
					
				};
			}
		});
		options.setCacheClassLookups(false); //Not sure if needed

My first tests seem to work. Now, the data, which is stored in Mongo is actually retrieved correctly and mapped to my nested POJOs.

While I understand the intention of this cache, I think it is wrong to use only `exists(Key<?> k)`. **At least** it must check the "version" (field annotated with `@version` in nested POJO) if available. 

I think this is really a bad bug, because it destroys data in standard config and I hope it will be addressed soon. Meanwhile, deactivating the cache may be a workaround.

PS: I think Morphia is great! Keep on the good work, but please also fix this issue :-)

**Comment by evanchooly** [comment]
There is now a flag to disable that caching.  see #476.  Doing that should correct this issue.  As old as it is, perhaps it no longer matters.  Please open a new issue should something come up.
