### ISSUE TITLE
Facing ConstraintViolationException issue : EntityCannotBeMapOrIterable

### ISSUE THREAD

**Issue by anshul-dhyani** [MorphiaOrg/morphia#1169]
I want to achieve schema-free model.
In order to achieve it I created a class which extends HashMap<String, Object>

Idea behind it was to add any extra field into data without changing code and hence avoiding rework.

but using Morphia when I annotate my class with @Entity it starts giving ConstraintViolationException issue : EntityCannotBeMapOrIterable.

If I dont give @Entity annotation then object is saved in DB but without the fields which I tried to insert using put method of map.(only fields declared in that  class are saved + 2 unnecessary things 1-> threshhold 2-> loadFactor)

This is how my class looks like 

//@Entity("enricheduserprofile")
public class EnrichedUserProfile extends HashMap<String, Object> implements Serializable{

        @Id
	private int rollNumber;
	private String name;

.
.
.
.
.
.
.}

if I try to do below thing in test 
EnrichedUserProfile eup = new EnrichedUserProfile(2, "rollnumber1");
 eup.put("occ1", "Eng");

object in DB looks like 

{
    "_id" : 2,
    "className" : "...EnrichedUserProfile",
    "name" : "rollnumber1",
    "threshold" : 0,
    "loadFactor" : 0.75
}

Is this a limitation with Morphia if Yes then can you please guide me to some work around.

Platform : Windows 10 64bit
Java version: 1.8.0_121
Morphia version : 1.2.1

**Comment by evanchooly** [comment]
It is a limitation (ancient) limitation in Morphia.  When i looked in to a while back it seemed to revolve around the ambiguity introduced by the fact that, in mongo, everything is a map so the morphia deserializer code gets befuddled with the Map as an entity type.

The workaround is to store your Map as a field on your entity.  It will introduce one level of indirection since you'll have to bounce all your get/put calls through that field but it resolve that ambiguity.  I've done this here and there and it works well enough.

**Comment by anshul-dhyani** [comment]
This workaround might not solve my problem. I want to store everything in the entity as different fields not as an extra map field holding all the extras so that i can query it much effectively and anyone consuming the APIs also does not gets affected.

**Comment by evanchooly** [comment]
This is a fundamental limitation in the mapping code for 1.x and 2.x.  Working around this is fraught with risks that outweigh the benefits at this point.  I'm going to close this as "won't fix."
