### ISSUE TITLE
AdvancedDatastore.ensureIndexes doesn't handle fields subtypes properly with version 1.3.2

### ISSUE THREAD

**Issue by dinosavings** [MorphiaOrg/morphia#1175]
Unit test:

public void testBadIndexing() {
        datastore.ensureIndexes(B.class);
        datastore.ensureIndexes(TestObject.class);
    }

    @Entity
    public static class TestObject {
        @Indexed
        private Long id;
        @Embedded
        private A a;
    }

    public static class A {
        @Indexed
        private Long id;
    }

    @Entity
    public static class B extends A {
        @Indexed
        private String url;
    }

Running testBadIndexing() generates the following exception

org.mongodb.morphia.mapping.MappingException: The path 'a.url' can not be validated against 'MyUnitTest$TestObject' and may represent an invalid index

	at org.mongodb.morphia.IndexHelper.calculateKeys(IndexHelper.java:264)
	at org.mongodb.morphia.IndexHelper.createIndex(IndexHelper.java:374)
	at org.mongodb.morphia.IndexHelper.createIndex(IndexHelper.java:366)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:959)
	at org.mongodb.morphia.DatastoreImpl.ensureIndexes(DatastoreImpl.java:954)

morphia version: 1.3.2
mongo driver version: 3.4.2 

This was working fine with morphia version .111.

**Comment by darklynx** [comment]
I have absolutely the same issue!

While debugging through the implementation I have found that `getSubTypes` method of [Mapper](https://github.com/mongodb/morphia/blob/master/morphia/src/main/java/org/mongodb/morphia/mapping/Mapper.java#L205) class is implemented incorrect: instead of sub-types (parent classes) it returns super-types (derivated / extended classes).

That is why [IndexHelper](https://github.com/mongodb/morphia/blob/master/morphia/src/main/java/org/mongodb/morphia/IndexHelper.java#L150) collects indexes from super classes that do not make sense in the parent class.

Please fix it.

**Comment by evanchooly** [comment]
Fixed with the PR merge
