### ISSUE TITLE
Adding Index to FindAndModify query

### ISSUE THREAD

**Issue by clementEchobox** [MorphiaOrg/morphia#1178]
Hi, 

I have noticed that it is not possible to set an index in FindAndModifyOptions , as it is in FindOptions in the following line:
`FindOptions.modifier("$hint", "index");
return query.asList(findOptions);`
Morphia 1.3 findAndModify seems to require to be written in the following manner: 
`findAndModify(Query, UpdateOperations, FindAndModifyOptions)`
Which prevents me from setting an index, since tneither findAndModifyOptions, nor update Operation seems to handle the setting of an Index. 
I also could not find any other way to do it. Is that intentional?

**Comment by MarcFletcher** [comment]
+1

**Comment by evanchooly** [comment]
Not only is this answer probably 2 years too late, but it's not intentional as such.  The database operation doesn't appear to [support](https://docs.mongodb.com/manual/reference/method/db.collection.findAndModify/) a `$hint` in this case and the driver certainly doesn't expose such a knob, either.  

I apologize for the delay.
