### ISSUE TITLE
TypeConverter skips first value conversion

### ISSUE THREAD

**Issue by mweiczorek** [MorphiaOrg/morphia#1349]
I'm trying to employ a TypeConverter to convert an object to a long value, and vice versa. When the document saves, the first value is not converted,but the rest are.

The POJO is a class that holds a single long timestamp value:

```
@Converters(TimeInstantConverter.class)
public class TimeInstant implements Serializable {

    private long timeValue = 0L;

    public TimeInstant() {
    }

    public TimeInstant(long timeValue) {
        this.timeValue = timeValue;
    }
    // other utility methods...
}
```

The specified converter:
```
public class TimeInstantConverter extends TypeConverter implements SimpleValueConverter {

    public TimeInstantConverter() {
        super(TimeInstant.class);
    }

    @Override
    public Object decode(Class<?> aClass, Object o, MappedField mappedField) {
        return new TimeInstant((long) o);
    }

    @Override
    public Object encode(Object value, MappedField optionalExtraInfo) {
        if (value == null)
            return 0L;
        return ((TimeInstant) value).getTimeValue();
    }
}
```
The document entity class that uses these values (fields redacted fro brevity):

```
@Entity(value = DbCollections.BOOKINGS, noClassnameStored = true)
public class Booking extends MongoDocument {

    public static final String SCHEDULED_AT = "scheduledAt";
    public static final String BOOKED_AT = "bookedAt";

    @Embedded(BOOKED_AT)
    private TimeInstant bookedAt = new TimeInstant();

    @Embedded(SCHEDULED_AT)
    private TimeInstant scheduledAt = new TimeInstant();
}
```
After saving a new `Booking` document:

```
{
    "_id" : ObjectId("5ce7e9edf79df2319c81348f"),
    "status" : "INITIALIZED",
    "bookedAt" : {
        "timeValue" : NumberLong(1558702573315)
    },
    "scheduledAt" : NumberLong(1558788973315)
}
```

The first field, `bookedAt` is saved differently (incorrectly), and subsequent fields are saved as the long value, as intended. It's always the first value that skips. If I change the order of the fields, the pattern holds:

```
{
    "_id" : ObjectId("5ce7e9a0f79df22a90d0c43a"),
    "status" : "INITIALIZED",
    "scheduledAt" : {
        "timeValue" : NumberLong(1558788896324)
    },
    "bookedAt" : NumberLong(1558702496324),
    "testing" : NumberLong(0)
}
```

Using `dev.morphia.morphia` version `1.4.1`

**Comment by evanchooly** [comment]
The problem here is that the `@Converters` annotation should be applied to the entity and not the converted type itself.  If you want to globally register that converter, you'd need to call `mapper.getConverters().addConverter(TimeInstantConverter.class)`.  Why you're seeing it work on the second field but not the first is that, during the processing of the fields, that annotation is discovered and subsequently registered.  There *is* a slight flaw in how *that* is done (it shouldn't register that converter like this) but considering it's worked this way for years now, I'm loathe to update it just now.  2.0 will clean this up, however, so it will be a bit more straightforward going forward.

**Comment by evanchooly** [comment]
will create a new issue for 2.0 to clean this up
