### ISSUE TITLE
Override getCollectionName() is a must for some use cases

### ISSUE THREAD

**Issue by qtxo** [MorphiaOrg/morphia#1368]
Not a problem with the current versions < 2 but the closing of Mapper methods for overriding is going to be a problem for us. 

Mapper.getCollectionName() is going to be deprecated and we currently use it like this:

```
Mapper mapper = new Mapper(options, baseMapper) {
            @Override
            public String getCollectionName(Object object) {

                String collectionName = super.getCollectionName(object);
                if (collectionSuffix != null) {
                    collectionName += "." + collectionSuffix;
                }
                return collectionName;
            }
        };
```

Where adding a collectionSuffix is very useful for 2 use cases:

1. Access the collection with a view for security, auditors, multi-tenant, etc. that returns the same mapped objects.

2. Writing to a temporary collection to rename it afterwards.

Also, note how this "hack" benefits from the "copy-constructor" `new Mapper(options, baseMapper)` to avoid scanning the same entities and packages again for each variation. I think version 2 is removing that useful feature as well.

**Comment by evanchooly** [comment]
Understood.  A lot of those deprecations are more to warn that the form/location/function might change in 2.0 based on the refactored API.  `getCollectionName()` will be there, probably, in some form because reference support requires some form of this.  Just be aware that these methods are internal methods for Morphia's needs and may change without warning.

**Comment by evanchooly** [comment]
For you use case, would it be sufficient to call `MappedClass.getCollectionName()`?
