### ISSUE TITLE
Why deprecated - Datastore.get(Class, id) & .delete(Class, id) ?

### ISSUE THREAD

**Issue by xtracoder** [MorphiaOrg/morphia#1381]
Hello, 

I'm migrating from v 1.3.2 (_because i could not workaroud the problem with Morphia's failure to start when it tries and fails to create unneded indices from sub-classes to non-entity super-classes_) and now I'm stubled upon question why following methods are deprecated in `interface Datastore`?

    T get(Class<T> clazz, V id);
    <T, V> WriteResult delete(Class<T> clazz, V id);

java doc says 'user delete(Query)', but that seems to be just unnecessary bunch of boilerplate code I need to add across plenty of places in my code.

Is there good reason for that? I tried looking for docs in this regard, but did not found something useful, for example here https://morphia.dev/1.5/getting-started/migration/

**Comment by evanchooly** [comment]
One of the goals of 2.0 is to modernize and simplify the API.  Where the current API makes heavy use of overloads, the new API is making more use of option classes and parameter objects.  As the number of optional parameters changes, keeping up with all the overloads necessary to provide a consistent API became prohibitively expensive. 

Additionally, the many different code paths available made testing complicated expensive to maintain.   Reducing tr
He surface area of the API allows me to focus in consistency and gives greater flexibility in evolving the API over time.

The 2.0 API is much more fluent providing a much more pleasant experience (I hope) but that comes at the cost of culling some methods and updating applications to make use of the new interfaces. 

I hope that answers your questions.  As the 2.0 APIs stabilize I'll be working to provide migration documentation and bridge APIs so that upgrading will be as painless as I can make it.
