### ISSUE TITLE
JPA-like refresh() method to load fields from database into a pre-existing entity

### ISSUE THREAD

**Issue by jonahseguin** [MorphiaOrg/morphia#1388]
**Please ask your question and provide whatever background or supporting information you think might be relevant:**

To my understanding, the Datastore#merge(object) method will $set all persistent fields in the passed object into the database for the object with matching objectID.

For a project I'm working on, I need to merge all the fields in the passed object **from** the database.  So that my transient fields in my object will remain untouched, and my object will be the same instance -- but the fields will be updated to the values from the database,

or even if there was a way to create a query with a pre-existing object to write the fields from the database to.
i.e 
`datastore.createQuery(MyClass.class, myObject)`

I'm wondering if this is already possible, I have searched for around an hour and have been unable to find anything for this use case!  Thanks.

**Please complete the following information:**

    Server Version: latest stable
    Driver Version: 3.11.0
    Morphia Version: 1.5.3

**Comment by jonahseguin** [comment]
Wondering if something like this would work, but looking through the code it seems like a pretty raw/unsafe method:

```java
public void updatePayloadFromNewer(X payload, X update) {
        this.payloadDatabase.getDatastore().getMapper().getMappedClass(payload).getPersistenceFields().forEach(mf -> {
            mf.setFieldValue(payload, mf.getFieldValue(update));
        });
    }
```

**Comment by jonahseguin** [comment]
Another possible way of doing it, although the fromDb method is deprecated?

Where update is the entity I loaded from database
And payload is the entity I want to update, from the database
```java
MyObject obj = datastore.getMapper().fromDb(datastore, datastore.getMapper().toDBObject(update), payload, datastore.getMapper().createEntityCache());
```

**Comment by jonahseguin** [comment]
still looking for a better solution to this

**Comment by evanchooly** [comment]
Sorry for the delay.  I've been heads down on 2.0 stuff.  I have two concerns with this request:

1.  I'm not sure this should be built in to Morphia as it's a pretty niche concern.
2.  #1 notwithstanding, I'm having a hard time picturing an API in 1.5 that would fill this need that would survive the transition to 2.0.  The mapping code has been heavily restructured and I haven't yet seen a decent way to get anywhere near this without severely torturing the internal APIs.

But, for me, #1 is the bigger question and my gut says Morphia shouldn't be doing this.  I'm open to persuasion but that's where my thinking is today.

**Comment by evanchooly** [comment]
`fromDB` is simply executing the deserialization code that Morphia uses when reading entities from the database.  This particular method call usually happens far below the surface where most users never have to worry about it.  Due to how Java visibility and accessibility work, it was made public some users started using it.  

In 2.0, however, the serialization code has been completely reworked to use the codec system the driver uses.  This will actually expose more functionality to power users should they choose to implement custom codecs and ensures that Morphia entities follow the same basic rules as everything else in the driver.  It also means, however, a little less flexibility in how that API can be used.

What your work around above is doing is writing out your entity to a `DBObject`, merging it with the `DBObject` retrieved from the database, and then hydrating it back in to an entity.  Honestly, what I might do in this case is simply write a utility method that would takes the loaded entity and the "real" one and copy values over, field by field, where the fields are null in the "real" version.  It'd be a simpler solution than plumbing the internals of Morphia which are *definitely* changing between 1.x and 2.x and could continue to evolve in 2.x as things are fine tuned.

**Comment by evanchooly** [comment]
There's a parallel from JPA so it's not as outlandish a concept for an ODM as my first instinct.  Will slate this for 2.0 and explore how reasonable the implmentation for 1.x would be.

**Comment by jonahseguin** [comment]
I appreciate it, thank you!
Looking forward to 2.0.

**Comment by jonahseguin** [comment]
Going to rename this to a more relevant title, copying the `refresh()` name from JPA

**Comment by evanchooly** [comment]
Easier than I thought it would be.  You can either build master yourself and try it out or I think I'll cut another ALPHA possibly BETA release this weekend.
