### ISSUE TITLE
when to release version 2.0?

### ISSUE THREAD

**Issue by grubed** [MorphiaOrg/morphia#1417]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
when to release version 2.0?

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version:

**Comment by evanchooly** [comment]
I'm hoping to do so in the next couple of months.  If you look at the [issues list](https://github.com/MorphiaOrg/morphia/milestone/24) you can see what I'm currently targeting for 2.0.  Some of those (e.g. new docs site) I'm not sure if i'd hold a release for just yet but the list is otherwise getting smaller by the week.  I'm wrapping up updates to new query/aggregation APIs that I'm hoping will be much more usable and maintainable and will probably do another ALPHA release.  In a few weeks I hope to start dropping BETA/RC releases for folks to try out as we approach a 2.0 final.

**Comment by d4nirod** [comment]
What driver/MongoDB version will Morphia 2 support? And by "support" I mean implementing the new DB features, let's say pipeline updates or transactions in Mongo 4.2 just to give an example... or the myriad operators that are usually changed or come out  with each new version.

**Comment by evanchooly** [comment]
The oldest version officially supported (and by that I mean tested) is 3.6 but 2.0 is being built and tested against 4.2 primarily and should offer access to "all" the features found there.  I have "all" in quotes because it's possible I've missed something but, e.g., I have tests that check against all the query and aggregation operations in the server docs and checks that they have implementations in Morphia.  Transactions are also supported, e.g., in 2.0.  Some of those news APIs are marked as experimental just to give a little room for refinement once they start seeing wider usage but having used them reasonably extensively in the tests, they feel pretty solid to me.

I'm hoping to cut a new pre-release (probably `-BETA1` this weekend and released on monday (ish.)  There should be `-SNAPSHOT` builds up on the sonatype snapshot repo already if you'd like to give it a try earlier.

**Comment by evanchooly** [comment]
2.0.0-BETA1 went out this morning.
