### ISSUE TITLE
UpdateOperations.set() with a null value should internally call unset()

### ISSUE THREAD

**Issue by Kktheoch** [MorphiaOrg/morphia#1437]
**Is your feature request related to a problem? Please describe.**
When updating from an Object we need to add null checks on each property that is updated and call either set() on non-null fields or unset() on fields that are null.

**Describe the solution you'd like**
On `UpdateOpsImpl.set()` should not throw a `QueryException` on null value, calling `unset()` with the field instead.

**Describe alternatives you've considered**

**Additional context**
This is on Morphia 1.3.1 but I suppose it stands true for newer releases as well.

**Comment by evanchooly** [comment]
Technically `unset()` and `set(null)` are not the same operation.  `unset` will remove a field from a document where setting it to null would leave the field in the document.

**Comment by janknobloch** [comment]
I think this is a very valid point especially looking at the 2.X Update API and presented online examples on how to use the library.

A mapper should behave in a similar manner for saving and updating entities.
Saving is done gracefully calling datastore.save(), persisting all attributes not containing a null value. - Great.!

Considering that the update() method or better stated the Update API behaves totally differently however, you have to explicitly set UpdateOperators.set() or UpdateOperators.unset() for each field.

This is a pain already as the API manually requires you to provide field-names - typos incoming....
not only that but you also have to check each field manually for null values before to assure its persisted properly.

So the point of setting potential incoming null values (pre-persist) to unset if existing in the database before
 and therefore removing them from the database is a totally valid point and for me at least an expected behaviour..

I don't fully understand how people actually using update functionality of morphia without writing their own wrappers checking fields with reflection or a like to mitigate this issue. 

Looking forward to get some input on how you envision using the api in regards to the example below:


` datastore.queryByExample(MyEntity.builder().withId(entity.getId()).build())
                .update(PLEASE SET AND UNSET ALL FIELDS HERE BASED ON NULL OR NON NULL?)
                .execute(options);`

**Comment by evanchooly** [comment]
As I mentioned earlier, `unset()` and `set(null)` are not the same operation so delegating to `unset()` like that would be incorrect.

As for the field names being typo-prone, consider using [critter](https://morphia.dev/critter/4.0/index.html).  It's a separate project right now but I'm seriously considering moving it in to morphia proper as a module instead.  I have a few things to do to critter first, though, before I make any such decision.

**Comment by janknobloch** [comment]
hey @evanchooly, thanks for your reply,
could you please elaborate how i would then incorporate an update() operation with upsert functionality without checking each field for null values and passing this to the new update api?

what i would like to do would be the following scenario:

1. insert record if not existing  (update with upsert - removing values that are null in the record to be placed)
2. if the record exists merge record using all existing fields of the new record as overwrite and removing (unset) all fields which are null in the document to be inserted.

right know this feels super cumbersome as one would have to check the entity (each field) via reflection or alike to determine null fields and than generating the UpdateOperation based on existing fields - if im not mistaken.

Another approach would be to try to insert or fetch the record first, than do a diff on the application logic side and than call an merge, this doesn't feel natural either.

**Comment by evanchooly** [comment]
OK.  That might be doable, actually.  I'll need to look at the code that does the saves but it shouldn't be terribly difficult to build a `$set` bucket of properties and a `$unset` bucket as part of the update statement in a `save()` call.  I'll open a new ticket with a more accurate title, though.

**Comment by janknobloch** [comment]
The title seems to be more accurate @evanchooly  thanks for looking into this, but since we where initially talking about updates / upserts, I would like to see the functionality on updates actually.

But thanks in first place for your efforts on this project, let me know where i can find the big fat spend me a coffee button. :-)


I'll try to elaborate briefly on my scenario (pseudo).
Maybe such a function could be called `updateOrUpsertExistingFields()` or alike.

Lets think about the following entity:

```
Entity{
val producer1; // is only part of the entity in the producer 1 project
val producer2; // is only part of the entity in the producer 2 project
}

```
The entity in the different projects does not contain all attributes(and their childs) purposely as a reason of information hiding / not carrying tons of subelements of entites in all projects. 

I have two producers and one consumer of my database:

The producer 1 i would like to call an update / upsert to insert val producer1;
The producer 2 i would like to call an update / upsert to insert val producer2;

On the consumer side of things, the consumer has the "full" entity and loads all variables and therefore the full record.

Right now im dealing with this in calling the following stack:
insert -> catch error if record already exists, -> merge -> catch unchanged error if exists , stop processing
(as merge as described sets all fields and actually contains the "correct" behaviour of also removing null fields)

This stack calls creates at least two ops (insert, merge) on the database and also i assume the change event will be an insert statement in the end instead of an update using merge. 

I think an update/upsert operation in a single fetch seems to be more reasonable?



Cheers 
Jan

**Comment by evanchooly** [comment]
Why wouldn't a `save(producer1)` work?  It would save what fields are on that object.  Now, the one thing I can think of is that `save()` currently replaces the document, iirc, which is obviously problematic.  But with the updated semantics from the new issue, this wouldn't be the case.  Essentially every save would be an upsert.

**Comment by janknobloch** [comment]
if i remember correctly its exactly as you described -> it overwrites (saves) the record an therefore removes the fields from producer2. I'll test again when i have a free minute. but i think im not mistaken.

**Comment by evanchooly** [comment]
The 2.2.0-SNAPSHOT has this implemented if you want to give it a try.  The documentation on the new feature can be found [here](https://morphia.dev/morphia/2.2/updates.html#_merges).
