### ISSUE TITLE
Embedded abstract class not working with 2.0.0?

### ISSUE THREAD

**Issue by stzanakis** [MorphiaOrg/morphia#1491]
How can I use abstract classes properly with 2.0.0
I used to have something similar to the below which used to work on the previous version:

```
@Entity
public class Root {
  private List<AbstractPlugin> plugins = new ArrayList<>();
  public Root() {
  }
...
}
```

```
@JsonTypeInfo(use = JsonTypeInfo.Id.NAME, include = As.EXISTING_PROPERTY, property = "pluginType")
@JsonSubTypes({
    @JsonSubTypes.Type(value = APlugin.class, name = "A_PLUGIN"),
    @JsonSubTypes.Type(value = BPlugin.class, name = "B_PLUGIN")
})
@Embedded
public abstract class AbstractPlugin{
...
}
```

With 2.0.0 I'm getting the following error:
`dev.morphia.mapping.MappingException: AbstractPlugin does not have a 0 argument constructor.`

Obviously adding an empty constructor doesn't work either with an error similar to:
`dev.morphia.mapping.MappingException: Can't instantiate the type AbstractPlugin: null`

The db also has the `className` field with the correct concrete class so after upgrading tbh I'm not sure if previously it was using the `pluginType` or the `className` to resolve which class the data represent.

What am I doing wrong and how can I make this work as before?

**Comment by evanchooly** [comment]
Can you build a [reproducer](https://github.com/MorphiaOrg/reproducer) and I'll take a look once I wrap up the issues I'm working on?  If not, i'll to recreate it myself.  Thanks.

**Comment by stzanakis** [comment]
Thanks for the reply, I think I've found why my specific implementation isn't working..
I will update tomorrow if I manage to fix it..

**Comment by stzanakis** [comment]
So finally I had overlooked the documents in the db and the embedded class did not have the className as I originally mentioned.

Anyway at the end of all this hassle I went through, I decided to just fix my issue by simply updating all documents in the db and adding the className field which was missing in the embedded document.

Nonetheless I created a reproducer because I'm curious if what I was trying was possible..
I believe in the previous version it was working but I haven't tested it thoroughly and I don't know if it was actually using the JsonTypeInfo annotations or not.

I've tried playing around with the Embedded annotation parameters but I did not succeed..
Here is the reproducer:
[reproducer](https://github.com/stzanakis/reproducer)

Is what I was trying possible with the 2.0.0?

**Comment by evanchooly** [comment]
OK.  I finally tracked it down.  I got distracted down the panicked "are abstract classes not getting mapped?!?" rabbit trail.  Because that would've been catastrophic.  But they are.  So here's what the problem is:

You've defined the discriminator key and that's fine.  That's working actually.  Looking in that field, it's finding the value "A_PLUGIN" but that value is never mapped to a class.  Adding this to `APlugin1` will fix your test:

```java
@Embedded(discriminator = "A_PLUGIN", discriminatorKey = "pluginType")
```

That will map the discriminator value to a specific type.  Otherwise, Morphia doesn't know how to find that class when it sees the discriminator.

On a slightly unrelated note, I'm not sure how wise it is to use an actual field in your class as the discriminator key.  I can imagine it makes sense in some cases and if it does in yours then by all means continue to do so.  But such fields are usually meta fields in the documents that have no business logic related to the entity itself.  Typically, they're "internal" implementation details that shouldn't be exposed to your application.  Still, though, if your app needs it that's fine.  It's just something to thing about.

Anyway, try adding that annotation to the class and see what that gets you.

**Comment by stzanakis** [comment]
I see yeah, I've tried that before and indeed it works but the issue here is that in the db the "`pluginType`" is inserted twice and this is not something desirable I think, right?
So the idea here is to re-use an existent field to recognize a class type and not create it.
Side note, perhaps an annotation that encapsulates all the possible types of a subclass could be part of the abstract class/interface(and not annotating each individual class), similarly with what jackson annotations are doing.

I mean I honestly thought that the jackson annotations were doing the trick on the previous versions but perhaps not.
Do in general jackson annotations work with morphia?
Is there a way to approach this or should we just stick with the "`className`" discriminator?

On the other regard, about the field being a meta field it is also used elsewhere so it was "reused" with morphia on the previous version, but in general I agree with you and it's something to look at..

**Comment by evanchooly** [comment]
OK.  That makes sense.  It's "weird" in some ways but not particularly "wrong."  Morphia isn't currently set up to make that work, I don't think.  Just thinking through the deserialization code, I'm pretty sure that key/value gets processed and discarded since it's typically a meta-field.  I don't think it'll be hard to correct that but I'm reasonably sure it won't work with what's out there to day.  I'll file a separate [issue](https://github.com/MorphiaOrg/morphia/issues/1491) to track that.

Morphia has never used the jackson annotations so you probably just got lucky.

**Comment by evanchooly** [comment]
I'm not seeing duplicate entries, fwiw:

```json
db.Root1.find().pretty()
{
        "_id" : ObjectId("5f70afe0c68c056c98660f1d"),
        "className" : "foo.Root1",
        "plugins" : [
                {
                        "pluginType" : "A_PLUGIN"
                }
        ]
}
```

**Comment by stzanakis** [comment]
Ehm I think you are checking at the end of the test, while in the test I'm removing one of the two duplicates.
The removal is happening at foo/ReproducerTest.java:70, so you need to check before that occurs.
Is that the case perhaps?

**Comment by evanchooly** [comment]
I was looking in the database directly right after the save...

**Comment by stzanakis** [comment]
Ok that's weird cause I'm seeing double. 
I'm using mongodb version 3.6.20.
