### ISSUE TITLE
Using @ConstructorProperties for better inter-op

### ISSUE THREAD

**Issue by pioorg** [MorphiaOrg/morphia#1555]
**Would it be possible to use `@ConstructorProperties` in Morphia?**

Hello @evanchooly 
I'd like to ask if the support for [@ConstructorProperties](https://docs.oracle.com/en/java/javase/11/docs/api/java.desktop/java/beans/ConstructorProperties.html) could be introduced/merged into Morphia?

As of now Morphia can also create `@Entity` or `@Embedded` objects using `ConstructorCreator`, which is checking if the constructor's parameters names are matching the attributes. For this to work Morphia requires that either the parameter names aren't obfuscated by the compiler, or that the names are specified verbatim using `@Name`.
However, there's also another approach, used e.g. with [Lombok](https://projectlombok.org/features/constructor) or [Jackson](https://github.com/FasterXML/jackson-databind/blob/11feb8846ea0e4a5a9490860d5a7e87b12aa3b28/src/test/java/com/fasterxml/jackson/databind/deser/creators/CreatorPropertiesTest.java#L8). It's using `@ConstructorProperties` annotation to specify parameters' names.
Having support for this could make Morphia more friendly e.g. when using `@Value`s and require less code when leaving parameter names is impossible.
Question: is there anything preventing Morphia from using `@ConstructorProperties` along with `@Name`? If not, I could create a PR for that.
Thank you

**Comment by evanchooly** [comment]
Already done:  https://morphia.dev/morphia/2.1/mapping.html#_constructors

**Comment by evanchooly** [comment]
Honestly, I'm disinclined, generally speaking, to allow for *too* many different ways to map things.  A big part of 2.0 was simplifying Morphia to reduce the learning curve and the surface area of the API.  Specifically, I'm *really* disinclined to work around such things as lombok because it opens a door to a number of complications I'd rather avoid both in terms of implementation and testing.

**Comment by pioorg** [comment]
Hi
Maybe I wasn't clear enough. It wasn't my intention to introduce or advertise any sort of Lombok support to construct entities or embedded parts. Not to mention any Lombok dependency in POM. ;-)
What I's like to say is that sometimes the constructor parameter names have to be defined explicitly (because they're not "compiled in"). In such case Morphia uses its own `@Name`, whereas other quite popular libs/frameworks/tools are using `@ConstructorProperties` (as demonstrated above).
This isn't a big deal for mutable beans, as they have the default constructor. However, for immutable ones (like `@Value`) this is really annoying, because they're using the full constructor. And many times such VOs/DTOs can perfectly fit in other places, even being part of the REST/JSON requests and responses.
Then such a class has not only to use `@ConstructorProperties`, but also quite a number of `@Name`s sometimes. Also, some entities can contain really a lot of such immutable POJOs. I think with records just around the corner the importance of handling immutable classes with full constructors as first class citizens is growing.

I can also use my example of migrating from Morphia 1 to Morphia 2 recently. We're using a lot of immutable types (like `@Value`) as data carriers in all layers and adding many lines with `@Name` felt like a ceremony, which could be perfectly avoided, because the classes were already annotated with `@ConstructorProperties`.

**Comment by evanchooly** [comment]
Sorry.  I haven't lost track of this I just got caught up in another issue.  I'm torn on this because I'd really rather not have multiple ways of mapping constructor parameters.  `@ConstructorProperties` is convenient for, say, lombok users, but `@Name` is much more refactor friendly.

I'm not following the "full constructor" argument, honestly.  Java records will have explicit constructor parameters for all its fields.  `@Name` is only needed when the parameter name does not match the field/property name.  If they match, the Morphia will bind one to the other.  `@Named` is only needed in the divergent cases.  I'm not familiar with the generated bytecode that, say, lombok emits but i'm willing to guess that the parameter names match the field names already and so `@Named` is not necessary.

**Comment by evanchooly** [comment]
I've been mulling this one over for a while and have kicked it around with the author of another mapper and his feedback was that something like `@ConstructorProperties` is much more fragile (both for users and the implementation) and that if I already have `@Name` that there's not really much value in introducing something else.  So for now, I'm going to close this as `wontfix` but certainly records might resurrect this.  My gut says we'll be ok there but we'll definitely test to be sure once I get a chance to focus on getting a java 16 build going.
