### ISSUE TITLE
Embedded annotation on fields

### ISSUE THREAD

**Issue by Peter0x48** [MorphiaOrg/morphia#1567]
Hi,

I opened #1467 last year while migrating to 2.0. Now (2.1.4) the Embedded annotation is still not applicable to fields. Should this be fixed?

Thanks!

Peter

**Comment by evanchooly** [comment]
No.  Embedded is a type annotation.  You don't need it on a field.  If you'd like to map a name for the property you can just use @Property like you would for any other field. 

More to the point, 2.2 is actually deprecating @Embedded because it doesn't really bring anything new to the table.  The end result is a much simpler mapping scheme using @Entity and @Property.

**Comment by evanchooly** [comment]
If you need to map an external type, see [here](https://morphia.dev/morphia/2.1/mapping.html#_external_types).

**Comment by Peter0x48** [comment]
Ok, thanks!
