### ISSUE TITLE
Is ValidationExtension(morphia); discontinued in version 2.1.4?

### ISSUE THREAD

**Issue by himnaz** [MorphiaOrg/morphia#1584]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **
Is ValidationExtension(morphia); discontinued in version 2.1.4? The version 2.1.4 documentation does not have a reference to it.

If discontinued can you please let us know how the validation will be handled?

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version:2.1.4

**Comment by evanchooly** [comment]
It's not so much discontinued as it has fallen in to disuse.  I wasn't sure if it was actually even used.  Since beginning to work on Morphia 8 or 9 years ago, I'm not sure I've ever actually had any requests related to it.  The tests seemed partial at best.  In short, it felt like a module that had been started but never finished.  If it's useful and needed we can certainly talk about reviving and modernizing.  But, honestly, this might be the first explicit mention of it I can recall so I just haven't given it any thought.

**Comment by evanchooly** [comment]
Is this something I should look at reviving in 2.3?

**Comment by christopher-cudennec** [comment]
Hi Justin!
I was just looking into migrating out Morphia 1.6 code to Morphia 2 and also came across this issue. We actively use `ValidationExtension` in our open source library [sda-dropwizard-commons](https://github.com/SDA-SE/sda-dropwizard-commons/). Would be nice to have it back. 😃

**Comment by evanchooly** [comment]
Then I'll make it happen.

**Comment by christopher-cudennec** [comment]
Just wanted to see if this would be something we can provide - but then I saw that you've just added the "validation" module ~ 2 weeks ago. 🥳 
Thanks in advance! Looking forward to the release! 👍

**Comment by evanchooly** [comment]
I'm closing this as this is tracked and completed elsewhere.

**Comment by christopher-cudennec** [comment]
Do you have plans for the next release? I'd like to try out Morphia 2 in our library. 🌈

**Comment by evanchooly** [comment]
You can see what's left in the 2.3 milestone
