### ISSUE TITLE
Significant performance decline with @Reference(idOnly = true) migrating from 1.4.1

### ISSUE THREAD

**Issue by ugljesas** [MorphiaOrg/morphia#1648]
I have a project that uses Morphia 1.4.1 that I'm looking to migrate to 2.2.

Running performance tests, I've found that certain workloads have degraded tremendously compared to the previous version. 

Doing some debugging I figured out it's connected to fetching multiple objects through query.iterator().toList() (previously query.asList()) that contain Reference(idOnly = true).

In the case of Lazy references, I've done a controlled test and only fetched the _id and the reference field, without actually accessing it, and there seems to be significant overhead compared to the previous version and fetching it as a plain ObjectId.

Non-lazy references seem to add even more overhead and performance degrades further compared to what I have in production. 

The consequence is that a request that fetches about 500 objects takes about 300ms with 1.4.1, but blows up to 2.5s with 2.2.1 on the same env. As a quick test, I've run the same workload using plain ObjectIds for references and handling them internally and the performance is about the same.

I would love some input on why this might be happening and if there is a workaround or fix in the works?

Server Version: 3.6.19
Driver Version: 4.2.2
Morphia Version: 2.2.1

**Comment by evanchooly** [comment]
I won't hold the 2.2.2 release for this one but I've been intending to set up a benchmarks project for a while now to track such regressions.  I'll make this the inaugural benchmark.

**Comment by h-arlt** [comment]
We observed performance degradation as well after migrating to Morphia v2. 
@evanchooly Did you find some time for further investigation and/or do have any updates on this?

**Comment by h-arlt** [comment]
Once we deployed Morphia v2 into our production system, CPU usage doubled in comparison to v1. After doing some profiling, we noticed that there were a lot of calls to `ReferenceCodec#createProxy()` and some of them took 6s or more. So we took a closer look at this method and realized that Proxy classes are generated for each and every instance of a given Reference type.

Since byte code generation and class loading is rather expensive, this should only be done once per Reference type and not once per instance. This [PR](https://github.com/MorphiaOrg/morphia/pull/1810)  adds caching of generated proxy classes to `ReferenceCodec` which improved overall performance in our production system significantly.
