### ISSUE TITLE
Custom enum codec

### ISSUE THREAD

**Issue by soundgarddden** [MorphiaOrg/morphia#1727]
Hi
Did I understand correctly that it is not possible to add your codec for enum classes to Morphia mapper? Will `dev.morphia.mapping.codec.EnumCodec` always be used?
I really do not want to depend on the name enum for interacting with the base.
`dev.morphia.mapping.codec.EnumCodecProvider` overrides codecs passed through the MongoClient.
I also want to choose a constant for enum through @Property, and not only through the codec

    Server Version: 4.2
    Driver Version: 4.2.2
    Morphia Version: 2.2.2

**Comment by soundgarddden** [comment]
It seems to me that the problem can be fixed by changing the order of codec providers

**Comment by evanchooly** [comment]
It could, yes, but that introduces other problems because Morphia needs its own codecs ahead of the drivers in certain cases.

**Comment by soundgarddden** [comment]
I will try to explain with specific examples. I decided to upgrade the morphia from version 1.5 to 2.2 on the project. Several enums were encoded and decoded through TypeConverter. I made codecs for these enums, as a result, morphia ignores them and uses its simple codec for enum.
I want to do without migrating the data in the database, and I also do not want any renaming of the enum constant to migrate already written data in the database, so using only Enum.valueOf () seems a rather bad solution.
Therefore, it seems to me that 2 modifications are needed:
1. EnumCodec should be used last after all more specific codecs.
2. EnumCodec must support mappedName for the enum constant, such as the @Property annotation

**Comment by evanchooly** [comment]
Well, the `EnumCodec` is only concerned with the value of the enum not the property name so i'm confused about that one.  But, otherwise, you want to store the ordinal of the enum rather than name of it yes?  That could probably just be switched via a new `MapperOption` value.  It would only work if *all* your enums are encoded that way.  At the moment, I don't see a way to manage individual properties separately with the existing system.

**Comment by soundgarddden** [comment]
https://github.com/MorphiaOrg/morphia/pull/1763
This version works well

**Comment by HaScooty** [comment]
We just encounterd the same problem.
We have an enum like:
public enum Brand implements {
  BrandX(30),
  BrandY(40),
  BrandZ(50));
 Where we store the value instead of the name in de Db. For now we, as described above, are unable to add a custom codec.

 Will a next version of Morphia support this, similar to how it supported custom converters in 1.6?
 Since we don't want to do a Db migration, we at the moment are unable to use our enum properly

**Comment by evanchooly** [comment]
I'm thinking at this point what it will probably look like is registering custom codec providers with the `Mapper` and those will take precedence over all the others.  This would be a 2.3 feature.

**Comment by christopher-cudennec** [comment]
That would be great! I think we also need that feature when migrating from 1.6 to 2.x! 👍

Since I had to search for quite some time what happened to the old converters approach, it would also be very helpful to get some documentation how things should be setup with Morphia 2.
