### ISSUE TITLE
Enable specifying an alternate collection to the mapped collection

### ISSUE THREAD

**Issue by newk5** [MorphiaOrg/morphia#1776]
Back with old morphia there was a way to save an object to a different collection with ```AdvancedDatastore#save(collection,object)``` how can I do this with version 2.2.3?

Server Version: 3.0.7
Driver Version: 4.3.4
Morphia Version: 2.2.3

**Comment by evanchooly** [comment]
That particular feature has been ... deferred ... since it does not interact well with other features (namely references) yet and a solution to that problem hasn't been realized just yet.

**Comment by evanchooly** [comment]
I have been tempted to put it back in with that caveat, honestly.   The old API was not great which was one of the issues I had with it.  I've contemplated reading the feature but using an option on the options type that can be passed in rather than the overload the old api used.   Would that work? 

I hate the idea of folks being stuck on 1.x as 2.x really does bring a lot of improvements.

**Comment by newk5** [comment]
You mean  adding a new property to ```InsertOneOptions/InsertManyOptions``` ? Yea that would work nicely.

**Comment by evanchooly** [comment]
Yeah, that's what I was thinking.  I'll add this to 2.3 then.
