### ISSUE TITLE
Query#modify() documentation is not entirely correct

### ISSUE THREAD

**Issue by nickel-bert** [MorphiaOrg/morphia#1830]
From the documentation (v.2.2):

> With this method, you can choose to return the updated entity in either the state before or after the update. 
**The default is to return the entity in the after state**. This can be changed by passing in a ModifyOptions reference to the operation

This is not entirely correct.
When executing the modify operation with **no** ModifyOptions I receive the **BEFORE** state of the entity (which is also the mongoDB default) and NOT the **AFTER** state as declared in the morphia documentation.

I also cannot see that the mongoDB default ReturnDocument value is overwritten when executing the modify operation : https://github.com/MorphiaOrg/morphia/blob/2.2.x/core/src/main/java/dev/morphia/query/Modify.java

So i think the docs should state:
_The default is to return the entity in the **before** state._

**Comment by evanchooly** [comment]
OK.  That should have been a quicker fix but I got sidetracked with other things.  The default is definitely _before_ as you said.  I don't know if that changed at some point and the docs fell behind or I just had a small embolism and messed it up.  At any rate, `Modify` doesn't actually do anything with that setting because the `ModifyOptions` in Morphia extends the driver options class so we can pass the reference in without needing to worry about copying or managing any of that.

Anyway, thanks for the heads up and apologies for the delay.
