### ISSUE TITLE
Does morphia support efficient bulk write operation?

### ISSUE THREAD

**Issue by zlinsplit** [MorphiaOrg/morphia#1856]
** Please ask your question and provide whatever background or supporting information you think might be relevant: **

There are times we have to insert a large list of objects at once. While Morphia does provide such method,
```
public <T> List<T> save(List<T> entities, InsertManyOptions options)
```
the implementation from `DatastoreImpl.java` simply calls `save()` on individual objects one at a time. This does not seem to be an efficient way for bulk writes, given that mongo does provide such capability. Is there any reason bulk write being implemented this way?

** Please complete the following information: **
    Server Version:
    Driver Version:
    Morphia Version: 2.2.2

**Comment by evanchooly** [comment]
If you look [here](https://github.com/MorphiaOrg/morphia/blob/e588d1078b13b8e969c9b208a1601680809f7bc2/core/src/main/java/dev/morphia/DatastoreImpl.java#L398) you'll see what's going on:

- If there's no ID value set or if the entity is versioned, it gets added to a List  <a>
- Otherwise, it gets add to a `Map` that maps a collection to a `List` of entities <b>
- You can ignore "alternate collection" stuff for now.  that's a 2.3 feature that won't affect you just yet.
- We then iterate over that `Map` from <b>, get the `MongoCollection`, and then call `insertMany()` with the `List` of entities mapped to that collection.  This will perform a bulk save which is handled for us by the driver itself.  We need only pass over the elements and it will perform the bulk ops for us.
- Once that is done, we then call `save()` for each individual element in the `List` from <a> because each of those will need to be handled individually for varying reasons.

Does that help answer your questions?

**Comment by zlinsplit** [comment]
@evanchooly Yes! Thanks!
