### ISSUE TITLE
Add @Polymorphic [moved]

### ISSUE THREAD

**Issue by jyemin** [MorphiaOrg/morphia#22]
This is [Issue 22](http://code.google.com/p/morphia/issues/detail?id=22) moved from a Google Code project.
Added by 2010-03-31T16:32:45.000Z by [scotthernandez](http://code.google.com/u/scotthernandez/).
Please review that bug for more context and additional comments, but update this bug.

Original labels: Type-Enhancement, Priority-Medium, Milestone-Release1.1
### Original description

```
Add support for storing (and searching on) the whole super-class tree and the interfaces implemented 
on any of them. Most likely this will be stored as an array of strings called super-classes 
(including the current class-name).

Something like this should be supported:

@Polymorphic
public class Shape {
}

public class Circle extends Shape {
}

public class Square extends Shape {
}

Datastore ds = ...;
List<Shape> shapes = ds.find(Shape.class).asList()
for(Shape shape : shapes)
  print(shape.getClass().getName());

> Circle
> Square
> Shape
> Circle
> Circle
```

**Comment by nosachamos** [comment]
This is major for me as well. I'm facing a lot of issues and having to resort to direct driver use to work around these issues as Morphia does not play nicely with polymorphic structures.

Say, if one has class A and B and C that inherit from them it seems natural that A could be annotated with @Polymorphic and all instances of A, B and C would then go to the A's collection. For each record, I like the idea of storing an array of class names going up in the type hierarchy for stored objects instead of the fully qualified name for the concrete implementation classes stored. This way one could query for instances of A, B, C or a combination of them and have them properly filtered and casted.

This is a major limitation and a bit discouraging to see it open from 2010... it's been 5 year after all :(

**Comment by nosachamos** [comment]
Just as a side not if anyone is interested in a work around, as for the example above instead of querying for
`datastore.find(Circle.class)`

...I am instead querying for:

`datastore.createQuery(Circle.class).disableValidation().filter("className =", Circle.class.getCanonicalName()).asList();` 

which works well but is a bit ugly. Also I don't know if we add an index to the `className` field but if we don't then this could make this query very slow for large data sets.

**Comment by ivmikhail** [comment]
+1 to issue

**Comment by ondevelop** [comment]
+1 to issue

**Comment by Fuzzo** [comment]
+1 to issue

**Comment by eugene-ivakhno** [comment]
+1 to issue

**Comment by SobiborTreblinka** [comment]
+1

**Comment by naveensky** [comment]
+1

**Comment by sgatade** [comment]
+1

**Comment by randm-ch** [comment]
+1

**Comment by aiaizhaoying** [comment]
+1

**Comment by mdoh** [comment]
any progress about that one?

**Comment by webermich** [comment]
I know this ticket is pretty old but I just wanted to provide an alternative.
Have a look at [Polymorphia](https://github.com/axelspringer/polymorphia)  
Among other things [Polymorphia](https://github.com/axelspringer/polymorphia) adresses the need to persist polymorphic data structures.  
It is based on the [java mongo driver](https://mongodb.github.io/mongo-java-driver/) and adds a codec to support POJOs. 
Also generic classes are supported. [Polymorphia](https://github.com/axelspringer/polymorphia) provides fine grained control over discriminator handling within the mongo database.
Give it a try and let me know, what you think.

**Comment by abulvenz** [comment]
Any opinions or progress about this issue? Otherwise we can start the 5 year celebration - if it didn't take place already ;-) Thanks @webermich for your effort, but changing the mapping to a different mechanism is not possible for me at the moment.

**Comment by evanchooly** [comment]
I actually have this done in my fork that I'm working on.  I've replaced the mapping code with the driver's POJO stuff i helped write.  It's getting pretty close to done.

**Comment by TheFlash787** [comment]
+1 🥇

**Comment by evanchooly** [comment]
working now in 2.0 though the `@Polymorphic` annotation isn't necessary.

**Comment by guss77** [comment]
@evanchooly Can you please explain how this should work in Morphia 2.4.2?

I tried:

```
// ... Junit setup...

	@Entity("shapes")
	public static class BaseShape {
		@Id
		protected ObjectId id;
		protected int sides;
	}

	@Entity("shapes")
	public static class Circle extends BaseShape {
		{ sides = 0; }
	}

	@Entity("shapes")
	public static class Triangle extends BaseShape {
		{ sides = 3; }
	}
	
	@Test
	void minimalTestCase() {
		log.info("Starting test");
		var ds = datastore();
		ds.getMapper().map(BaseShape.class, Circle.class, Triangle.class);
		ds.save(new Circle());
		ds.save(new Triangle());
		log.info("Trying to find shapes");
		ds.find(BaseShape.class).forEach(s -> {
			log.info("Found: " + s);  // --> nothing was printed from here
		});
		log.info("These were all the shapes");
	}
```

If I save an instance of `BaseShape` - then that can be found. If I search for any of the child types, I find only instance of that specific sub-type.

**Comment by evanchooly** [comment]
You have to enable [polymorphic queries](https://morphia.dev/morphia/2.4/queries.html#_polymorphic_queries).
