### ISSUE TITLE
Create multiple Datastore objects (Two Database connections) 

### ISSUE THREAD

**Issue by zarubto4** [MorphiaOrg/morphia#2456]
i am using version 2.4. 

In last version we had 4 databases and we used  ` createDatastore(mongoClient, dbName) `,
but now its deprecated and its allowed to use it only by file.  How I can use it? 

I find file-only configuration to be " NOT BEST IDEA", because some systems connect to the database using External Inputs and it is not known in advance where they will connect. Also problem like this is not possible to solved by file.

**Comment by glasen** [comment]
I've the same question. Our code connects to multiple databases whose names we don't know in advance. The databases are created dynamically in our code and their names are provided by normal, non-developing, users at run-time.

**Comment by evanchooly** [comment]
Multiple datastore support is definitely on the way.  The dynamic creation of the metadata is ... problematic for this particular course so we'll definitely have to explore some options here.  Other than the database names, is everything else static and documentable in a file?  What does the rest of the config look like?

Also, it sounds like you're implementing a form of multitenancy which is also in the plan for 3.0 which might help mitigate some of these conflicts.  Am I reading that wrong?

**Comment by glasen** [comment]
> Other than the database names, is everything else static and documentable in a file? What does the rest of the config look like?
In my case, yes. The only two things which define at runtime in our code is the URI-string for the MongoDB-connection and the name of the database. Everything else is static and can be set by a config file.

> Also, it sounds like you're implementing a form of multitenancy which is also in the plan for 3.0 which might help mitigate some of these conflicts. Am I reading that wrong?
Not really. In my case, we use different databases for storing data of different legal cases (Documents, e-mails, binary data, etc.). All cases use the same structure (collection-names and schemas) but because of legal reasons each case must be separated from each other.

Normally you would use an MongoDB instance for each customer or legal case, but we are talking of many TBs of uncompressed data (In one case ~60 TB and over 500 million documents). And because we don't know how much space a case will need in before, everything is stored in a big sharded MongoDB-installation (Multiple servers).

My question about the changes in version 2.4 is why did you do it? The builder-pattern worked perfectly, at least for me.

**Comment by shahr** [comment]
I also would like to request programmatic configuration style to be supported alongside the file-based configuration. Our use case is primarily to provide default configuration (via a library) to a wide variety of projects to keep things consistent in terms of our own internal best practices.

Another reason for needing programmatic configuration is that we also like to keep everything in a single configuration file rather than have many files for many things as this tends to increase cognitive complexity for new or junior members of the team.

I love Morphia and, as a library for the masses, it seems overly restrictive to only allow it to be used in exactly one way. Please please please, continue to support programmatic configuration for Morphia.

**Comment by shahr** [comment]
Thanks for the reply @evanchooly. I think something like an InputStream would work for us. An overlay would be very helpful so we can could provide default configuration and override as needed. Ideally we should be able to specify where configuration files are sourced from (rather than just the default in META-INF/...).done

To be perfectly honest, startup times for us are not a big issue so discovery of classes to map at runtime is not a big deal. For us, the bigger impact is on tightly managing how configuration is provided which is easiest when it is programmatic.

All that said, if you could link your PR here when you've got a proposed approach, I'd be happy to help test it out and provide any feedback.

As always, appreciate the help and support. Thank you!

**Comment by evanchooly** [comment]
That's great feedback.  Thanks.  It's probably the first thing i'll tackle on the 3.0/master branch to provide plenty of time for feedback and refinements.  The last thing I want is to trip you all up for the sake of internal conveniences.  If we can find a workable solution, I'd definitely consider a 2.5 backport to help you migrate to whatever, if any, the new set up would look like in the interim between now and 3.0.

**Comment by evanchooly** [comment]
I'm rolling back the `MapperOptions` deprecations in light of the feedback. I'll take a deeper look in to what changes might be made to make a cleaner path forward.  I have a better idea now all the myriad ways Morphia is being used I didn't before so I have that to take in to consideration now which is fabulous. I've updated the docs already.
