### ISSUE TITLE
Performance issue when using transactions

### ISSUE THREAD

**Issue by h-arlt** [MorphiaOrg/morphia#2629]
**Describe the bug**
Since #2569 , creation of morphia sessions involve several copy operations and hash calculations. Doing so seems to be very expensive in terms of resource consumption.

According to the (very simplified) test case stated below, more and more time is spent while CPU goes crazy each time a new session is created.
I wasn't even able to perform a deletion operation inside a transaction 10 times in a row within several minutes before I had to terminate the Java process forcibly.

PS: TBH I don't really understand why all this copy stuff is necessary for a "simple client-session capture". Why not using the same mapper in MorphiaSession as the originating datastore? Having multiple independent datastores is definitely another story. 
This is not meant as complain but merely as personal observation. You are doing a great job with Morphia and we are really happy to use it. However, the rework that was done in #2569 currently prevents us from updating to v2.4.5+  as we make heavy usage of transactions to perform deletion of entities that are related in form of a hierarchy (aka cascading delete). Hence, transaction performance is quite critical for us.

**To Reproduce**
Run test case stated below.

**Expected behavior**
Transactions perform similar to Morphia v2.2.x or v2.3.x in terms of time and memory.

**Please complete the following information:**
 - Server Version: 7.0
 - Driver Version: 4.11.0
 - Morphia Version: 2.4.6

**Additional context**

Demo Test
```java
package dev.morphia.test;

import static org.testng.Assert.assertEquals;

import java.time.LocalDate;
import java.util.Stack;

import org.bson.types.ObjectId;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.testng.annotations.BeforeMethod;
import org.testng.annotations.DataProvider;
import org.testng.annotations.Test;

import com.mongodb.client.result.DeleteResult;

import dev.morphia.query.filters.Filters;
import dev.morphia.test.models.User;

public class TestTransactionalDelete extends TestBase
{
    private static final Logger LOG = LoggerFactory.getLogger(TestTransactionalDelete.class);

    private final Stack<ObjectId> entityIDs = new Stack<>();

    @BeforeMethod
    public void before()
    {
        checkMinServerVersion(4.0);
        checkForReplicaSet();

        getDs().getCollection(User.class).drop();
    }

    @DataProvider(name = "demo-sizes")
    public Object[] sizes()
    {
        return new Object[] {5, 10, 15};
    }

    @Test(dataProvider = "demo-sizes")
    public void delete(int demoSize)
    {
        insertData(demoSize);

        int round = 0;
        while (!entityIDs.isEmpty())
        {
            ++round;

            final ObjectId _id = entityIDs.pop();
            LOG.info("[Round {}] Goting to delete User having ID '{}'", round, _id);

            final long start = System.nanoTime();
            final DeleteResult deleteOutcome = getDs().withTransaction((session) -> session.find(User.class)
                                                                                           .filter(Filters.eq("_id", _id))
                                                                                           .delete());
            final long end = System.nanoTime();

            assertEquals(deleteOutcome.getDeletedCount(), 1L);
            LOG.info("[Round {}] Deletion of single entity took {} nanos", round, (end - start));

        }
    }

    private void insertData(final int demoSize)
    {
        for (int i = 0; i < demoSize; i++)
        {
            final User savedEntity = getDs().save(new User("Test User " + String.valueOf(i + 1), LocalDate.now()));
            entityIDs.push(savedEntity.getId());
        }
    }
}

```

**Comment by evanchooly** [comment]
The copy stuff is a bit ... complicated.  When a transaction is started, you get a specialized instance of the `Datastore` except it's called a `MorphiaSession` (to mirror the driver jargon).  When you do any operation via that `MorphiaSession`, it passes along the driver session and everything happens inside that transaction.  Now due to historical decisions largely driven limitations in the driver, some of the codecs for properties have references to the `Datastore`. If that reference was populated before the transaction, you'll have the old datastore and not the transactional one so you'll operate outside of the transactional boundaries. If that reference is set *during* the transaction, operations afterwards will try to use that old session and get a server failure.  A couple of attempts to detangle that were made without success. The "easy" fix was to copy over the mappings (without rescanning the entities, note...) and then let those `Datastore` reference get populated as they do and when the transaction ends, they would all get GC'd away and automatically cleaned up.

I'm a little surprised you're seeing a performance hit with that as the copying is kept to a minimum and there isn't any new scanning done (typically.  Morphia will still dynamically map an `@Entity` annotated type it has seen before but that late mapping behavior is being phased out for various reasons.)  I haven't seen any issues with it in the tests but I'll certainly run yours and see if anything pops.

I know this long response doesn't fix things yet but I hope the context of the decisions helps in the interim.  I'm working on a batch of new releases across different versions and I'll do my best to rectify this as much as I can before the next 2.4 release.

**Comment by evanchooly** [comment]
Though I did just notice that you're starting a new transaction for each delete which seems ... suboptimal.

**Comment by h-arlt** [comment]
> Though I did just notice that you're starting a new transaction for each delete which seems ... suboptimal.

Yep. This is done intentionally to mimic our cascading delete use-case which performs deletion of related entities within separate transactions.

**Comment by h-arlt** [comment]
It looks like there is spent more and more time in computing EntityModel hash codes. Don't know (haven't analyzed this yet) if some resources pile up in memory although they are expected to be cleaned up when session ends.

PS: It's not related to this issue but I also noticed that the copy c'tor in EntityModel processes the subtypes somewhat unexpected; instead of adding a copy of the other's subtype to self, a copy of self is added to other's subtype :thinking:

**Comment by h-arlt** [comment]
> I know this long response doesn't fix things yet but I hope the context of the decisions helps in the interim. I'm working on a batch of new releases across different versions and I'll do my best to rectify this as much as I can before the next 2.4 release.

Thanks for clarification and the historic outline. I know that things get complicated over the years, esp. when more and more features are expected by users to be supported while still being backwards compatible.

**Comment by evanchooly** [comment]
> It looks like there is spent more and more time in computing EntityModel hash codes. Don't know (haven't analyzed this yet) if some resources pile up in memory although they are expected to be cleaned up when session ends.
> 
> PS: It's not related to this issue but I also noticed that the copy c'tor in EntityModel processes the subtypes somewhat unexpected; instead of adding a copy of the other's subtype to self, a copy of self is added to other's subtype 🤔

Curious.  I'll take an extra careful look through that code.  It's behaving as expected so I'd be surprised to find anything but then I also didn't expect, or detect, such a significant perf hit either.  Thanks for bringing that to my attention.

**Comment by evanchooly** [comment]
I reworked that code and it's quite snappy now.  2.4.7-SNAPSHOT should be updated in the next hour or so if you want to give it a try.  I think that was the last issue for 2.4.7 so I'll try to release it this weekend.

**Comment by evanchooly** [comment]
I'll push 2.4.7 tonight.

**Comment by h-arlt** [comment]
Awesome. Thx!
