### ISSUE TITLE
Datastore.get(Class<T>, Iterable<V>) generates invalid query when Iterable<ObjectId> parameter is empty. 

### ISSUE THREAD

**Issue by sirusdv** [MorphiaOrg/morphia#565]
```
@Test
public void testEmptyIdList() throws Exception {
        assertEquals(0, getDs().get(Hotel.class, new ArrayList<ObjectId>()).asList().size());
}
```

Tests in error: 
  testEmptyIdList(org.mongodb.morphia.TestQuery): invalid query

Looks like mongo gets queried with:

```
{ _id: { $in: null } }
```

which is invalid.

**Comment by fgouguenheim** [comment]
Hello.

In our case, we don't want to activate "setStoreEmpties", and we don't want to add a "!isEmpty" test before each "in" call in our code.

To us, it should be Morphia's work to correctly handle the empty Collection in queries so that "query.field(field).in(empty)" should transform into a "{field:{$in:{}}}" query rather than "{field:{$in:{null}}}".

Is it possible to fix this bug for Morphia version 1 ?

(problem found in IterableConverter::encode(Object value, MappedField mf) : should return empty list instead of null when value is empty collection).

Thks
