### ISSUE TITLE
saving empty list results in null saved

### ISSUE THREAD

**Issue by umbreak** [MorphiaOrg/morphia#626]
Same as [this post](https://github.com/mongodb/morphia/issues/263), which comes from the original [here](https://code.google.com/p/morphia/issues/detail?id=263). At some point in the original thread a project member (scotthernandez) agrees that, indeed, that's a bug, but it looks like it is not solve yet.

**An empty object is not the same than a null one**, mainly for `@override equals` and `@override hashCode`. Now, my OBJECT comparison finds the objects to be different, since when I save them it could be and empty object, and when I fetch it back for comparison it turns out to be null. 

It is very important to keep the equals contract for everything to work as expected....

**Comment by zaid2130** [comment]
@evanchooly this solution is not work for me. I am getting null fields whereas I have declared tham as emptyList. I have added your line just after server starts. After adding your line with it's dependency my mongo is saving same null fields. Any solution? 
I am using MongoSession instead of MongoCodecSession in grails 3.1

**Comment by zaid2130** [comment]
@evanchooly Yes. 
https://github.com/MorphiaOrg/morphia/issues/1292

**Comment by zaid2130** [comment]
Actually, I am upgrading Grails 3.0 to Grails 3.1.16, and I am using MongoSession instead of MongoCodecSession because I am using nativeEntry which causes problems in MongoCodecSession. The actual problem that I am getting in MongoSession in grails 3.1 that it was saving null fields which causes not to $push anything on null fields. Have you understand my problem?

**Comment by zaid2130** [comment]
Or it's great if you can tell me how to use nativeEntry in Grails 3.1 i.e in MongoCodecSession. 
I am using MongoCodecSession like this for nativeEntries but I am not getting my document in a correct format as I was getting in MongoSession in grails 3.0. Does MongoCodecSession needs some other properties or it's not working fine with inline query? 
d.class.withNewSession { MongoCodecSession m ->
            m.persist(d)
            nativeRec = m.pendingUpdates.find {
                it.key.name == d.class.getName()
            }.value[0].nativeEntry.region[0]."${instance.getDbKey()}"[0]
        }
