### ISSUE TITLE
EntityCannotBeMapOrIterable - why is this a validation constraint?

### ISSUE THREAD

**Issue by gaspardpetit** [MorphiaOrg/morphia#910]
Hi,

I am trying to understand why Morphia validates that entities do not implement the Map interface?  In our case, we use a custom mapper and this is valid.  

I was trying to find the way to bypass the validation.  Since it is performed when the BasicDAO is constructed, I thought of passing a Mapper which already contained an unvalidated entity, but I could not find how to do that  - I cannot call addMappedClass with validation set to false since it is private on the Mapper class.

Any pointer would be greatly appreciated!

Gaspard

**Comment by evanchooly** [comment]
That part predates my involvement but partly it seems to be due to the @Id requirement on entities.  I'm digging through the validation test case to see what can be done.

**Comment by evanchooly** [comment]
OK.  So this constraint is in place because generics mapping is ... limited in the current mapper.  The new mapper on the could probably support it but we need to get other bits in place before we can confirm that works.

**Comment by evanchooly** [comment]
Actually, while investigating a related issue, I realized this is because mapping a Map creates an ambiguous scenario where it's uncertain which fields should be mapped and which shouldn't.  Without requiring `@Property` annotations on fields, it's nearly impossible to know which fields on the Map-based entity to map to the database and which not.
