### ISSUE TITLE
DatastoreImpl:tryVersionedUpdate should more descriptive than just ConcurrentModificationException

### ISSUE THREAD

**Issue by gorazdio** [MorphiaOrg/morphia#982]
`DatastoreImpl:tryVersionedUpdate` throws a `ConcurrentModificationException` when there is a version conflict. 

My usecase for the Morphia's `@Version` feature actually exposes the version via a REST API (ETag) and allows for optimistic locking on API level. However there is no clean way to catch the specific exception when version is violated, since it's such a generic exception.

You would normally expect `ConcurrentModificationException` to be throws when there is a bug in the implementation. In fact javadoc states:

> Therefore,it would be wrong to write a program that depended on this exception for its correctness: ConcurrentModificationException should be used only to detect bugs

If not replacing the type of exception, I believe it should at least be subclassed, so that it's more specific to the case.

**Comment by plaa** [comment]
I agree.  I'm probably going to wrap the exception in a `MorphiaConcurrentModificationException` class in the save methods that I fortunately have.

Like @gorazdio said, ideally the exception would not extend `ConcurrentModificationException` since that is intended only for bug detection, but that would be in incompatible API change.

**Comment by evanchooly** [comment]
ConcurrentModificationException does not indicate a bug in the implementation, necessarily.  It indicates that two conflicting operations are being performed.  And that's exactly what's happening here:  you're trying to save two different versions of the same entity.  You're concurrently modifying a versioned entity.  The best that can be done here is to subclass CME but I'm loathe to introduce a new type for such questionable gain.

**Comment by plaa** [comment]
From the [JavaDoc](https://docs.oracle.com/javase/7/docs/api/java/util/ConcurrentModificationException.html):

> Therefore, it would be wrong to write a program that depended on this exception for its correctness: _ConcurrentModificationException should be used only to detect bugs._

Regardless how you interpret the documentation, I have never seen a `ConcurrentModificationException` except in case of a bug.  In the case of Morphia, there is a very valid use-case where the version is passed in through an API.

In my case I want to convert the exception to a specific HTTP status code returned by Jersey.  Fortunately I have wrapper classes for all modification actions, so I can catch the CME and wrap it into my own custom exception.  Otherwise it would be impossible to distinguish the exception thrown by Morphia from a bug in my code.

**Comment by evanchooly** [comment]
Most exceptions only show up in the presence of bugs.  In this case, the bug is your application is trying to modify an outdated version of the entity.  At any rate, I can't really change the exception type coming out now and subclassing only papers over any concerns about suitable of using CME in the first place.

**Comment by plaa** [comment]
The use case presented by @gorazdio is not a bug.  It's publishing the version number over an API.  If the requester uses an old version number, the exception is triggered and an appropriate error is returned by the requester.  This provides reliable optimistic locking over the API.

I'm also converting the exception to an appropriate API response code.  Fortunately, my code is structured so that all write operations come through only a handful of methods, and I can catch the CME there and throw a more specific exception.  If my code would be structured otherwise, I would be in trouble.  Either I would be unable to convert the optimistic locking exception to the appropriate API response, or I would be potentially masking and converting other coding bugs as well (i.e. CME's from iterators).

Discussion on whether `ConcurrentModificationException` is appropriate or not is semantics, and I'm not proposing breaking API compatibility by removing it.  But there are very valid use cases where it is necessary to catch specifically optimistic locking exceptions created by Morphia, and that's not possible if it throws a CME instead of a distinct subclass.

**Comment by evanchooly** [comment]
maybe old age has changed me but, yeah, a subclass would help.  I would just outright use a new exception but that'd break folks who've caught this one explicitly.  Maybe in 3.0, we can remove that parent class and have it stand on its own...
